---
- name: Populate sysctl configuration file lists
  set_fact:
    role_systemparameters_list: '{{ role_systemparameters_list | default([]) + vars[item] }}'
  loop: "{{ vars.keys() | select('match', '^role_systemparameters_sysctl_list_.*$') | list }}"
  tags:
    - tag_role_systemparameters_deploy_templates
    - tag_role_systemparameters_remove_files

- name: Populate modprobe configuration file lists
  set_fact:
    role_systemparameters_list: '{{ role_systemparameters_list | default([]) + vars[item] }}'
  loop: "{{ vars.keys() | select('match', '^role_systemparameters_modprobe_list_.*$') | list }}"
  tags:
    - tag_role_systemparameters_deploy_templates
    - tag_role_systemparameters_remove_files

- name: Populate kernel modules configuration file lists
  set_fact:
    role_systemparameters_list: '{{ role_systemparameters_list | default([]) + vars[item] }}'
  loop: "{{ vars.keys() | select('match', '^role_systemparameters_kernelmodules_list_.*$') | list }}"
  tags:
    - tag_role_systemparameters_deploy_templates
    - tag_role_systemparameters_remove_files

- name: Populate limits configuration file lists
  set_fact:
    role_systemparameters_list: '{{ role_systemparameters_list | default([]) + vars[item] }}'
  loop: "{{ vars.keys() | select('match', '^role_systemparameters_limits_list_.*$') | list }}"
  tags:
    - tag_role_systemparameters_deploy_templates
    - tag_role_systemparameters_remove_files

- name: Deploy sysctl configuration files from template
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    backup: '{{ item.backup | default(omit) }}'
    attributes: '{{ item.attributes | default(omit) }}'
    owner: '{{ item.owner | default("root") }}'
    group: '{{ item.group | default("root") }}'
    mode: '{{ item.mode | default("0644") }}'
    block_start_string: '{{ item.block_start_string | default(omit) }}'
    block_end_string: '{{ item.block_end_string | default(omit) }}'
    variable_start_string: '{{ item.variable_start_string | default(omit) }}'
    variable_end_string: '{{ item.variable_end_string | default(omit) }}'
    lstrip_blocks: '{{ item.lstrip_blocks | default(omit) }}'
    trim_blocks: '{{ item.trim_blocks | default(omit) }}'
    newline_sequence: '{{ item.newline_sequence | default(omit) }}'
    output_encoding: '{{ item.output_encoding | default(omit) }}'
    selevel: '{{ item.selevel | default(omit) }}'
    serole: '{{ item.serole | default(omit) }}'
    setype: '{{ item.setype | default(omit) }}'
    seuser: '{{ item.seuser | default(omit) }}'
    unsafe_writes: '{{ item.unsafe_writes | default(omit) }}'
    follow: '{{ item.follow | default(omit) }}'
    force: '{{ item.force | default(omit) }}'
    validate: '{{ item.validate | default(omit) }}'
  loop: '{{ role_systemparameters_list }}'
  notify: sysctl_load_system
  when:
    - item.state == 'present'
  tags:
    - tag_role_systemparameters_deploy_templates

- name: Cleanup unwanted configuration files
  file:
    path: '{{ item.dest }}'
    state: absent
  loop: '{{ role_systemparameters_list }}'
  when:
    - item.state == 'absent'
  tags:
    - tag_role_systemparameters_remove_files

...
